# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: "4.4.stable"

    steps:
    # ───── Checkout ────────────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ───── Go toolchain & cache ───────────────────────────────────────────────
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # ───── Go static analysis & tests ─────────────────────────────────────────
    - name: go vet
      working-directory: Server
      run: go vet ./...

    - name: Unit tests
      working-directory: Server
      run: go test ./tests/unit/... ./pkg/... -coverprofile=coverage.out -v

    - name: Integration tests
      working-directory: Server
      run: go test ./tests/integration/... -v

    - name: Upload Go coverage
      uses: actions/upload-artifact@v4
      with:
        name: go-coverage
        path: Server/coverage.out

    # ───── Godot headless & GDScript lint ─────────────────────────────────────
    - name: Set up Godot (headless)
      uses: lihop/setup-godot@v2
      with:
        version: ${{ env.GODOT_VERSION }}
        alias: godot    # «godot» появится в $PATH

    - name: Install gdtoolkit (gdlint / gdformat)
      run: pip install gdtoolkit

    - name: Lint GDScript
      working-directory: CardGame
      run: gdlint -e .

    # ───── GUT tests ──────────────────────────────────────────────────────────
    - name: Run GUT tests
      working-directory: CardGame
      run: |
        godot -q --headless \
          -s addons/gut/gut_cmdln.gd \
          -gdir=res://tests \
          -gexit \
          -gjunit_xml_file=res://tests/report.xml

    - name: Upload GUT JUnit report
      uses: actions/upload-artifact@v4
      with:
        name: gut-report
        path: CardGame/tests/report.xml

